// <auto-generated />
using AlperAslanApps.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using RowinPt.DataAccess;
using System;

namespace RowinPt.DataAccess.Migrations
{
    [DbContext(typeof(RowinPtContext))]
    partial class RowinPtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RowinPt.Domain.AbsenceNotesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("AbsenceNotes");
                });

            modelBuilder.Entity("RowinPt.Domain.AgendaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<Guid>("ScheduleItemId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("RowinPt.Domain.CourseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("Capacity");

                    b.Property<Guid>("CourseTypeId");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CourseTypeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("RowinPt.Domain.CourseTypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("Capacity");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CourseTypes");
                });

            modelBuilder.Entity("RowinPt.Domain.LocationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RowinPt.Domain.MeasurementModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<float?>("ArmSize");

                    b.Property<float?>("BellySize");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<float?>("FatPercentage");

                    b.Property<float?>("ShoulderSize");

                    b.Property<float?>("UpperLegSize");

                    b.Property<float?>("WaistSize");

                    b.Property<float?>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("RowinPt.Domain.ScheduleItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("CourseId");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<TimeSpan>("EndTime");

                    b.Property<Guid?>("PersonalTrainerId");

                    b.Property<Guid>("ScheduleId");

                    b.Property<TimeSpan>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PersonalTrainerId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("RowinPt.Domain.ScheduleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<Guid>("LocationId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("RowinPt.Domain.SubscriptionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("CourseTypeId");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<string>("Notes");

                    b.Property<DateTime?>("RecentEntry");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("WeeklyCredits");

                    b.HasKey("Id");

                    b.HasIndex("CourseTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("RowinPt.Domain.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("EditedBy")
                        .IsRequired();

                    b.Property<DateTime>("EditedOn");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedEmail")
                        .IsRequired();

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<Guid>("SecurityStamp");

                    b.Property<byte>("Sex");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserModel");
                });

            modelBuilder.Entity("RowinPt.Domain.CustomerModel", b =>
                {
                    b.HasBaseType("RowinPt.Domain.UserModel");

                    b.Property<DateTime?>("BirthDate");

                    b.Property<int?>("Length");

                    b.Property<string>("Number");

                    b.ToTable("CustomerModel");

                    b.HasDiscriminator().HasValue("CustomerModel");
                });

            modelBuilder.Entity("RowinPt.Domain.PersonalTrainerModel", b =>
                {
                    b.HasBaseType("RowinPt.Domain.UserModel");

                    b.Property<bool>("Admin");

                    b.ToTable("PersonalTrainerModel");

                    b.HasDiscriminator().HasValue("PersonalTrainerModel");
                });

            modelBuilder.Entity("RowinPt.Domain.AbsenceNotesModel", b =>
                {
                    b.HasOne("RowinPt.Domain.CustomerModel", "Customer")
                        .WithOne("AbsenceNotes")
                        .HasForeignKey("RowinPt.Domain.AbsenceNotesModel", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RowinPt.Domain.AgendaModel", b =>
                {
                    b.HasOne("RowinPt.Domain.CustomerModel", "Customer")
                        .WithMany("Agenda")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RowinPt.Domain.ScheduleItemModel", "ScheduleItem")
                        .WithMany("Agenda")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RowinPt.Domain.CourseModel", b =>
                {
                    b.HasOne("RowinPt.Domain.CourseTypeModel", "CourseType")
                        .WithMany("Courses")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RowinPt.Domain.MeasurementModel", b =>
                {
                    b.HasOne("RowinPt.Domain.CustomerModel", "Customer")
                        .WithMany("Measurements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RowinPt.Domain.ScheduleItemModel", b =>
                {
                    b.HasOne("RowinPt.Domain.CourseModel", "Course")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RowinPt.Domain.PersonalTrainerModel", "PersonalTrainer")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("PersonalTrainerId");

                    b.HasOne("RowinPt.Domain.ScheduleModel", "Schedule")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RowinPt.Domain.ScheduleModel", b =>
                {
                    b.HasOne("RowinPt.Domain.LocationModel", "Location")
                        .WithMany("Schedules")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RowinPt.Domain.SubscriptionModel", b =>
                {
                    b.HasOne("RowinPt.Domain.CourseTypeModel", "CourseType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RowinPt.Domain.CustomerModel", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
