export const AUTHENTICATION_AUTHENTICATE_START = "AUTHENTICATION_AUTHENTICATE_START";
export const AUTHENTICATION_AUTHENTICATE_SUCCESS = "AUTHENTICATION_AUTHENTICATE_SUCCESS";
export const AUTHENTICATION_AUTHENTICATE_FAIL = "AUTHENTICATION_AUTHENTICATE_FAIL";
export const AUTHENTICATION_AUTHENTICATE_RESET = "AUTHENTICATION_AUTHENTICATE_RESET";

export const ACTIVATION_START = "ACTIVATION_START";
export const ACTIVATION_ERROR = "ACTIVATION_ERROR";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";

export const APPLICATION_SETTINGS_SET = "APPLICATION_SETTINGS_SET";