// api
export const API_CALL_START = "API_CALL_START";
export const API_CALL_STOP = "API_CALL_STOP";
export const API_RESET = "API_RESET";
export const API_SET_RESULT = "API_SET_RESULT";
export const API_SUBMIT_SUCCESS = "API_SUBMIT_SUCCESS"
export const API_DELETE_SUCCESS = "API_DELETE_SUCCESS";
export const API_RESET_ALL = "API_RESET_ALL";

// validation modal
export const VALIDATION_OPEN_MODAL = "VALIDATION_OPEN_MODAL";
export const VALIDATION_CLOSE_MODAL = "VALIDATION_CLOSE_MODAL";

// error
export const ERROR_MODAL = "ERROR_MODAL";
export const ERROR_LOAD = "ERROR_LOAD";
export const ERROR_RESET = "ERROR_RESET";

// app settings
export const APPLICATION_SETTINGS_SET = "APPLICATION_SETTINGS_SET";

// authentication
export const AUTHENTICATION_START_LOADER = "AUTHENTICATION_START_LOADER";
export const AUTHENTICATION_LOGOUT_SUCCESS = "AUTHENTICATION_LOGOUT_SUCCESS";
export const AUTHENTICATION_CHALLENGE_SUCCESS = "AUTHENTICATION_CHALLENGE_SUCCESS";

// userinformation
export const SET_USER_INFORMATION = "SET_USER_INFORMATION";